steps:
- name: gcr.io/cloud-builders/docker
  args:
  - build
  - -f
  - infra/docker/ingestor.Dockerfile
  - -t
  - asia-southeast1-docker.pkg.dev/steam-491906/steamweb/daily-ingest:latest
  - .
images:
- asia-southeast1-docker.pkg.dev/steam-491906/steamweb/daily-ingest:latest
