steps:
- name: gcr.io/cloud-builders/docker
  args:
  - build
  - -f
  - infra/docker/bot.Dockerfile
  - -t
  - asia-southeast1-docker.pkg.dev/steam-491906/steamweb/bot:latest
  - .
images:
- asia-southeast1-docker.pkg.dev/steam-491906/steamweb/bot:latest
